PORT: 9089
PREFIX: api

getToken: http://127.0.0.1:8088/ssologin/getToken
checkToken: http://127.0.0.1:8088/ssologin/checkToken
oaAppid: 3d077166-676e-4ec8-a9c0-706c6a89c36b
# 数据库配置
datasource:
  driverName: mysql
  host: www.db4free.net
  port: 3306
  database: dev_wintsa
  username: wintsa
  password: 12300114
  charset: utf8
  loc: Asia/Shanghai
  logging: true


#企业微信配置
wxChat:
  corpsecret: YbF5JHEjAKWuO5-5nLf5xuH2R1wFc8pGBWTq0fyE12s
  CorpID: ww97588d93c357248d
  AgentId: 1000004
  Token: KxvcyR3SQqTIzAVyIQTn2
  Key: Fc3rx5pyQ4BePDDT7t5jHOvTzfdVbBDgySDhbebWDAq
  dakaSecret: 06J216adGcxmj2YaDiUI7F2bwGWBiaS6XcMuYwVbMZI
  tongXunSecret: -dAuFs4uhcyOjpkHgxDrvPV8gdNb7OPvJW3odGeCua4
  OaSecret: tdSkeup7gRnpDa9EfLG0scV0cElrX9pqkvJJVHVw7bI
  OA2Secret: YbF5JHEjAKWuO5-5nLf5xuH2R1wFc8pGBWTq0fyE12s

# 腾讯地图api
TxKey: LX7BZ-UQZ6Q-ANJ5N-4I4XJ-G6DZ6-7AFVI
TXSecretKey: jd3SQgZZvl2Xenpa1V7pe8dXrLnRiKLg
# 阿里oss存储(可直接使用)
aliyunOss:
  accessKeyId: 'LTAI4FmwbKtoErzJdwfJmcmd'
  accessKeySecret: 'bu5UZXAG2dXQ6G75bzTDXoTN1VcALv'
  endpointUrl: 'oss-cn-shenzhen'
  bucketUrl: 'https://an-jia-shop.oss-cn-shenzhen.aliyuncs.com'
  bucketName: 'an-jia-shop'
  imgDefaultSize: 5
  supportImgTypes: ['.png', '.jpg', '.gif', '.jpeg']
#法大大
fadada:
  appId: '00000876'
  appSecret: S1NAPOWD45VIXDMI9NL0S3NKSDVM6H3G 
  serverUrl: https://api.fadada.com/api/v5/
  opencorpId: 15ad1a994ed746dbbc2420840308d7a6
  businessId: d065d6947bfb545df69faaaff10868a5
# fadada:
#   appId: '80000470'
#   appSecret: FQCLPQRNNIZXVLX1NQDBS10DUZJ8HNFQ
#   serverUrl: https://uat-api.fadada.com/api/v5
#   opencorpId: b665596642694fa39a11e22ca5cdc704
#   businessId: 3b68a1ff1e851c69ba4c70c2b1997421
#豸印

zhiyin:
  url: https://www.zhiyinseal.com/smartsealservice/
  appId: 9koctjctghthidy60frqc4uab2hjevk1
  appKey: inxz77e5woa4ql6n3o4ciaohbxm0flb8
  AgentId: 1000023


ipWhitelist: ['127.0.0.1','192.168.2.1','192.168.2.221']